/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'design-pages': DesignPage;
    products: Product;
    'product-categories': ProductCategory;
    posts: Post;
    comments: Comment;
    programs: Program;
    'site-settings': SiteSetting;
    enrollments: Enrollment;
    orders: Order;
    reviews: Review;
    classrooms: Classroom;
    ebooks: Ebook;
    referrals: Referral;
    coupons: Coupon;
    webhook_events: WebhookEvent;
    waitlists: Waitlist;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'design-pages': DesignPagesSelect<false> | DesignPagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    classrooms: ClassroomsSelect<false> | ClassroomsSelect<true>;
    ebooks: EbooksSelect<false> | EbooksSelect<true>;
    referrals: ReferralsSelect<false> | ReferralsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    webhook_events: WebhookEventsSelect<false> | WebhookEventsSelect<true>;
    waitlists: WaitlistsSelect<false> | WaitlistsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  phone?: string | null;
  role: 'admin' | 'user';
  mustResetPassword?: boolean | null;
  importedFrom?: string | null;
  googleId?: string | null;
  kakaoId?: string | null;
  naverId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-pages".
 */
export interface DesignPage {
  id: number;
  title: string;
  slug: string;
  projectData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  html?: string | null;
  css?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * 예: vibe-coding-101 — 이 값으로 /store/{slug} URL이 만들어짐
   */
  slug: string;
  subtitle?: string | null;
  shortDescription?: string | null;
  productType: 'class' | 'ebook' | 'book' | 'bundle';
  /**
   * 카드 상단에 표시. 예: "강의" / "전자책 / 종이책"
   */
  category?: string | null;
  price?: number | null;
  originalPrice?: number | null;
  /**
   * 가격이 없는 외부 판매 등. 예: "교보문고 판매 중"
   */
  priceLabel?: string | null;
  /**
   * 있으면 D-N 카운트다운이 카드/상세에 표시됨
   */
  discountUntil?: string | null;
  /**
   * 체크하면 결제 페이지/상품 상세 CTA가 대기 신청 폼으로 분기. 다음 기수 오픈 안내용 명단만 받음.
   */
  waitlistMode?: boolean | null;
  /**
   * 대기 신청 폼 상단에 표시. 예: "2기는 모집이 마감되었습니다. 3기 모집이 시작되면 가장 먼저 안내드립니다. 가격은 변동될 수 있습니다."
   */
  waitlistNotice?: string | null;
  /**
   * 예) 슈퍼얼리버드/얼리버드/정가 단계별 가격을 시작일시와 함께 등록. 시작일시가 되면 자동으로 해당 가격이 적용됩니다. 비워두면 위 "판매가"가 그대로 적용됩니다. 입력 순서는 자유 — 시스템이 시간순으로 자동 정렬합니다.
   */
  priceSchedule?:
    | {
        startAt: string;
        price: number;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 구매하기, 외부 링크 등
   */
  actions?:
    | {
        label: string;
        url: string;
        primary?: boolean | null;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 예: AI 웹사이트 구축, 4주 과정, 온라인
   */
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  duration?: string | null;
  /**
   * 이 상품 전용 질문/답변. 상세 페이지에 노출
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 강의 상품인 경우 결제 완료 시 여기 입력한 슬러그의 강의실 입장 권한이 자동 부여됩니다. 책/전자책은 비워두세요. 기수가 다르면 별도 강의실을 만들어 슬러그를 등록하세요. 예: vibe-coding-advanced-2
   */
  grantedClassroomSlugs?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  classroomSlug?: string | null;
  /**
   * 전자책 상품일 때 PDF를 직접 업로드하세요. 매 다운로드 요청마다 인증을 거쳐 1회성 스트리밍으로 제공됩니다. (구글 드라이브 등 외부 링크보다 보안 강력)
   */
  ebookFile?: (number | null) | Ebook;
  /**
   * 레거시 전자책에만 사용. 새 상품은 위 ebookFile에 PDF를 직접 업로드하세요. ebookFile이 있으면 이 값은 무시됩니다.
   */
  downloadUrl?: string | null;
  /**
   * 예: "파일 용량이 크니 다운로드 후 보관해 주세요." 마이페이지와 결제 완료 메일에 표시됩니다.
   */
  downloadNote?: string | null;
  /**
   * 체크하면 결제 시 배송지 입력 폼이 노출됩니다.
   */
  requiresShipping?: boolean | null;
  /**
   * 카드 목록에 표시되는 정사각형 이미지
   */
  thumbnail?: (number | null) | Media;
  /**
   * 캔바 등으로 만든 상세 이미지를 순서대로 추가
   */
  detailImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  status: 'published' | 'draft';
  featured?: boolean | null;
  seoType?: ('Product' | 'Course' | 'Book') | null;
  seoAuthor?: string | null;
  description?: string | null;
  content?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ebooks".
 */
export interface Ebook {
  id: number;
  /**
   * 예: 불편한 AI 전자책 v1.0
   */
  title: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  name: string;
  slug: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  content: string;
  author?: string | null;
  category?: ('free' | 'question' | 'share' | 'notice') | null;
  status?: ('draft' | 'published') | null;
  views?: number | null;
  pinned?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  post: number | Post;
  author: string;
  content: string;
  status?: ('approved' | 'pending') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  version?: string | null;
  downloadUrl?: string | null;
  platform?: ('windows' | 'mac' | 'linux' | 'web' | 'all') | null;
  category?: ('utility' | 'ai-tool' | 'plugin' | 'other') | null;
  thumbnail?: (number | null) | Media;
  status?: ('draft' | 'published') | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  /**
   * 홈페이지 URL 경로 (예: /home)
   */
  homePath?: string | null;
  navigation?:
    | {
        /**
         * 메뉴 표시 이름
         */
        label: string;
        /**
         * URL 경로 (예: /store, /contents)
         */
        path: string;
        type: 'home' | 'store' | 'community' | 'programs' | 'custom';
        /**
         * 커스텀 페이지 슬러그 (type이 custom일 때만)
         */
        customPageSlug?: string | null;
        enabled?: boolean | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  name: string;
  phone: string;
  email: string;
  program: string;
  message?: string | null;
  status?: ('pending' | 'confirmed' | 'paid' | 'cancelled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  buyerName: string;
  buyerEmail: string;
  buyerPhone?: string | null;
  user?: (number | null) | User;
  productName: string;
  productSlug?: string | null;
  productType?: ('class' | 'ebook' | 'book' | 'bundle') | null;
  amount: number;
  originalAmount?: number | null;
  payMethod?: ('card' | 'vbank' | 'trans' | 'phone' | 'kakaopay' | 'naverpay' | 'tosspay') | null;
  status:
    | 'pending'
    | 'paid'
    | 'active'
    | 'completed'
    | 'refund_requested'
    | 'refunded'
    | 'failed'
    | 'cancel_requested'
    | 'cancelled';
  paidAt?: string | null;
  impUid?: string | null;
  merchantUid?: string | null;
  pgProvider?: string | null;
  receiptUrl?: string | null;
  vbankName?: string | null;
  vbankNum?: string | null;
  vbankDate?: string | null;
  depositorName?: string | null;
  referredByCode?: string | null;
  referrerUser?: (number | null) | User;
  referralRewardKrw?: number | null;
  referralPaidOutAt?: string | null;
  couponCode?: string | null;
  couponDiscountKrw?: number | null;
  refundReason?: string | null;
  refundedAt?: string | null;
  refundAmount?: number | null;
  refundBank?: string | null;
  refundAccountNum?: string | null;
  refundAccountHolder?: string | null;
  cashReceiptType?: ('none' | 'income' | 'expense') | null;
  cashReceiptNumber?: string | null;
  shippingRecipient?: string | null;
  shippingPhone?: string | null;
  shippingZipcode?: string | null;
  shippingAddress?: string | null;
  shippingAddressDetail?: string | null;
  shippingMessage?: string | null;
  shippingStatus?: ('pending' | 'preparing' | 'shipping' | 'delivered') | null;
  trackingNumber?: string | null;
  shippingCarrier?: string | null;
  adminMemo?: string | null;
  classrooms?:
    | (
        | 'vibe-coding-101'
        | 'vibe-coding-advanced'
        | 'vibe-coding-101-2'
        | 'vibe-coding-advanced-2'
        | 'vibe-coding-101-3'
        | 'vibe-coding-advanced-3'
        | 'vibe-coding-101-4'
        | 'vibe-coding-advanced-4'
      )[]
    | null;
  books?: ('personal-intelligence' | 'uncomfortable-ai' | 'prompt-15' | 'notebooklm-guide')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  product?: (number | null) | Product;
  /**
   * 회원이 직접 작성한 경우 자동 연결됩니다. 매니저가 임의로 추가하는 경우 비워두고 displayName을 사용하세요.
   */
  user?: (number | null) | User;
  /**
   * 매니저가 임의로 후기를 추가할 때 사용. 회원 후기인 경우 비워두면 회원 이름이 사용됩니다.
   */
  displayName?: string | null;
  rating: number;
  content: string;
  siteUrl?: string | null;
  status: 'pending' | 'approved' | 'rejected';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classrooms".
 */
export interface Classroom {
  id: number;
  /**
   * 예: AI 바이브 코딩 [심화] 2기 — 백지 위의 바이브코더
   */
  title: string;
  /**
   * 예: 바이브 코딩 심화 2기
   */
  shortTitle: string;
  /**
   * 예: vibe-coding-advanced-2 — 이 값으로 /classroom/{slug} URL이 만들어짐
   */
  slug: string;
  /**
   * 1기, 2기 등. 같은 강의의 다른 차수를 구분
   */
  cohort?: number | null;
  description?: string | null;
  level?: ('입문' | '심화' | '특강') | null;
  /**
   * 강의실 상단에 표시. 예: 매주 수 21시, 4회차
   */
  schedule?: string | null;
  /**
   * 있으면 강의실 상단에 강조 표시
   */
  liveUrl?: string | null;
  resourceUrl?: string | null;
  /**
   * 각 회차의 영상, 가이드북, 비밀자료를 등록
   */
  sessions?:
    | {
        week: number;
        title: string;
        date?: string | null;
        /**
         * 있으면 우선 표시. 예: 1186484969
         */
        vimeoId?: string | null;
        /**
         * vimeoId 없을 때만 표시. 라이브 종료 후엔 vimeoId로 교체
         */
        youtubeLiveUrl?: string | null;
        guidebookUrl?: string | null;
        secretEnabled?: boolean | null;
        secretPassword?: string | null;
        secretNotionUrl?: string | null;
        /**
         * 기본값: '비밀 자료 열기'
         */
        secretLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'active' | 'draft' | 'closed';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrals".
 */
export interface Referral {
  id: number;
  /**
   * 예: CHOI23. 발급 시 자동 생성됨
   */
  code: string;
  user: number | User;
  status: 'active' | 'disabled';
  payoutBank?: string | null;
  payoutAccountNum?: string | null;
  payoutHolder?: string | null;
  memo?: string | null;
  /**
   * 집계 시 자동 갱신. 정확한 값은 주문 조회로 산출.
   */
  totalReferrals?: number | null;
  totalRewardKrw?: number | null;
  paidOutKrw?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  /**
   * 발급 시 자동 생성. 사용자가 직접 입력하지 않음.
   */
  code: string;
  user: number | User;
  discountType: 'percent' | 'amount';
  discountPercent?: number | null;
  discountAmount?: number | null;
  source?: ('referral' | 'admin' | 'campaign') | null;
  referralCode?: string | null;
  status: 'active' | 'redeemed' | 'expired' | 'cancelled';
  expiresAt?: string | null;
  redeemedAt?: string | null;
  redeemedOrderNumber?: string | null;
  memo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * PortOne 등 외부 웹훅 수신 로그. dedup·재처리·디버깅 용도.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook_events".
 */
export interface WebhookEvent {
  id: number;
  /**
   * PortOne의 webhook-id 헤더 값. 같은 ID는 두 번 처리되지 않음.
   */
  webhookId: string;
  source: 'portone' | 'other';
  eventType?: string | null;
  paymentId?: string | null;
  status: 'pending' | 'processing' | 'processed' | 'ignored' | 'failed';
  attempts?: number | null;
  lastError?: string | null;
  processedAt?: string | null;
  /**
   * 디버깅용 raw body. 민감정보 없음(서명 검증 후 저장).
   */
  rawPayload?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 모집 마감 후 대기 신청 명단. 다음 기수 오픈 시 일괄 안내.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlists".
 */
export interface Waitlist {
  id: number;
  /**
   * 예: vibe-coding-101 — 이 슬러그로 모집 알림 발송 대상 추출
   */
  productSlug: string;
  productName?: string | null;
  buyerName: string;
  buyerEmail: string;
  buyerPhone?: string | null;
  motivation?: string | null;
  /**
   * 비로그인 신청은 비어있음
   */
  user?: (number | null) | User;
  status: 'active' | 'notified' | 'converted' | 'cancelled';
  notifiedAt?: string | null;
  /**
   * 예: 인스타·블로그·검색 등 — 추후 마케팅 분석용
   */
  source?: string | null;
  adminMemo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: 'users' | 'orders' | 'waitlists';
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'design-pages';
        value: number | DesignPage;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'classrooms';
        value: number | Classroom;
      } | null)
    | ({
        relationTo: 'ebooks';
        value: number | Ebook;
      } | null)
    | ({
        relationTo: 'referrals';
        value: number | Referral;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'webhook_events';
        value: number | WebhookEvent;
      } | null)
    | ({
        relationTo: 'waitlists';
        value: number | Waitlist;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  role?: T;
  mustResetPassword?: T;
  importedFrom?: T;
  googleId?: T;
  kakaoId?: T;
  naverId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-pages_select".
 */
export interface DesignPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  projectData?: T;
  html?: T;
  css?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  shortDescription?: T;
  productType?: T;
  category?: T;
  price?: T;
  originalPrice?: T;
  priceLabel?: T;
  discountUntil?: T;
  waitlistMode?: T;
  waitlistNotice?: T;
  priceSchedule?:
    | T
    | {
        startAt?: T;
        price?: T;
        label?: T;
        id?: T;
      };
  actions?:
    | T
    | {
        label?: T;
        url?: T;
        primary?: T;
        external?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  duration?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  grantedClassroomSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  classroomSlug?: T;
  ebookFile?: T;
  downloadUrl?: T;
  downloadNote?: T;
  requiresShipping?: T;
  thumbnail?: T;
  detailImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  order?: T;
  status?: T;
  featured?: T;
  seoType?: T;
  seoAuthor?: T;
  description?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  author?: T;
  category?: T;
  status?: T;
  views?: T;
  pinned?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  post?: T;
  author?: T;
  content?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  version?: T;
  downloadUrl?: T;
  platform?: T;
  category?: T;
  thumbnail?: T;
  status?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  homePath?: T;
  navigation?:
    | T
    | {
        label?: T;
        path?: T;
        type?: T;
        customPageSlug?: T;
        enabled?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  program?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  buyerName?: T;
  buyerEmail?: T;
  buyerPhone?: T;
  user?: T;
  productName?: T;
  productSlug?: T;
  productType?: T;
  amount?: T;
  originalAmount?: T;
  payMethod?: T;
  status?: T;
  paidAt?: T;
  impUid?: T;
  merchantUid?: T;
  pgProvider?: T;
  receiptUrl?: T;
  vbankName?: T;
  vbankNum?: T;
  vbankDate?: T;
  depositorName?: T;
  referredByCode?: T;
  referrerUser?: T;
  referralRewardKrw?: T;
  referralPaidOutAt?: T;
  couponCode?: T;
  couponDiscountKrw?: T;
  refundReason?: T;
  refundedAt?: T;
  refundAmount?: T;
  refundBank?: T;
  refundAccountNum?: T;
  refundAccountHolder?: T;
  cashReceiptType?: T;
  cashReceiptNumber?: T;
  shippingRecipient?: T;
  shippingPhone?: T;
  shippingZipcode?: T;
  shippingAddress?: T;
  shippingAddressDetail?: T;
  shippingMessage?: T;
  shippingStatus?: T;
  trackingNumber?: T;
  shippingCarrier?: T;
  adminMemo?: T;
  classrooms?: T;
  books?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  user?: T;
  displayName?: T;
  rating?: T;
  content?: T;
  siteUrl?: T;
  status?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classrooms_select".
 */
export interface ClassroomsSelect<T extends boolean = true> {
  title?: T;
  shortTitle?: T;
  slug?: T;
  cohort?: T;
  description?: T;
  level?: T;
  schedule?: T;
  liveUrl?: T;
  resourceUrl?: T;
  sessions?:
    | T
    | {
        week?: T;
        title?: T;
        date?: T;
        vimeoId?: T;
        youtubeLiveUrl?: T;
        guidebookUrl?: T;
        secretEnabled?: T;
        secretPassword?: T;
        secretNotionUrl?: T;
        secretLabel?: T;
        id?: T;
      };
  status?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ebooks_select".
 */
export interface EbooksSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrals_select".
 */
export interface ReferralsSelect<T extends boolean = true> {
  code?: T;
  user?: T;
  status?: T;
  payoutBank?: T;
  payoutAccountNum?: T;
  payoutHolder?: T;
  memo?: T;
  totalReferrals?: T;
  totalRewardKrw?: T;
  paidOutKrw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  user?: T;
  discountType?: T;
  discountPercent?: T;
  discountAmount?: T;
  source?: T;
  referralCode?: T;
  status?: T;
  expiresAt?: T;
  redeemedAt?: T;
  redeemedOrderNumber?: T;
  memo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook_events_select".
 */
export interface WebhookEventsSelect<T extends boolean = true> {
  webhookId?: T;
  source?: T;
  eventType?: T;
  paymentId?: T;
  status?: T;
  attempts?: T;
  lastError?: T;
  processedAt?: T;
  rawPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlists_select".
 */
export interface WaitlistsSelect<T extends boolean = true> {
  productSlug?: T;
  productName?: T;
  buyerName?: T;
  buyerEmail?: T;
  buyerPhone?: T;
  motivation?: T;
  user?: T;
  status?: T;
  notifiedAt?: T;
  source?: T;
  adminMemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    name?: string | null;
    format: 'csv' | 'json';
    limit?: number | null;
    page?: number | null;
    sort?: string | null;
    sortOrder?: ('asc' | 'desc') | null;
    drafts?: ('yes' | 'no') | null;
    selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
    fields?: string[] | null;
    collectionSlug: string;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    userID?: string | null;
    userCollection?: string | null;
    exportCollection?: string | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}